# Generated by Django 3.0.3 on 2020-04-24 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='title',
            field=models.CharField(default='Title', max_length=45),
        ),
    ]
